name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Verify NPM token
        run: if [ -z "${{ secrets.NPM_TOKEN }}" ]; then echo "NPM_TOKEN is not set"; exit 1; fi

      - name: Check if version is published
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if npm view vue-color@$VERSION > /dev/null 2>&1; then
            echo "Version $VERSION already exists. Skipping publish."
            exit 1
          fi

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
