name: Run some checks before releasing

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # run on pull_request events that target the main branch
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run link

      - name: Build
        run: npm run build

      - name: Demo Build
        run: npm run demo:build