name: Run tests and upload coverage

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # run on pull_request events that target the main branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies (root)
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run root tests
        run: npm run coverage

      - name: Install and run Vue 2.7 tests
        working-directory: vue2
        run: |
          npm ci
          npm run test

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

